{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "intelligent-wallet-ledger.fullname" . }}-api
  labels:
    {{- include "intelligent-wallet-ledger.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "intelligent-wallet-ledger.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  policyTypes: [Ingress]
  ingress:
    - ports:
        - protocol: TCP
          port: http
{{- end }}
