{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "intelligent-wallet-ledger.serviceAccountName" . }}
  labels:
    {{- include "intelligent-wallet-ledger.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
